name: ğŸ—‘ï¸ Purge untagged images

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
# Run cleanup job if a new package was published or updated
on:
  registry_package:

jobs:
  purge_untagged_images:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§¹ clean packages
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GHCR_TOKEN}}
          organization: ${{ github.repository_owner}}
          container: ${{ github.event.repository.name }}
          prune-untagged: true